// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBVyq4SC69m-Fpgl1fvuBIsTFmXRQlT8',
    appId: '1:1090505053172:web:4c81745b8eab8c20551fa1',
    messagingSenderId: '1090505053172',
    projectId: 'english-mate-699fb',
    authDomain: 'english-mate-699fb.firebaseapp.com',
    storageBucket: 'english-mate-699fb.firebasestorage.app',
    measurementId: 'G-805DKBZLXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6whfyK9dcMtGZYIn8LyTl5rJUVVxUymI',
    appId: '1:1090505053172:android:f4ad246082dc910a551fa1',
    messagingSenderId: '1090505053172',
    projectId: 'english-mate-699fb',
    storageBucket: 'english-mate-699fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwIoK1BN9rHalLwmif9waW7EbEATFDsE',
    appId: '1:1090505053172:ios:32c55f05a5a111fc551fa1',
    messagingSenderId: '1090505053172',
    projectId: 'english-mate-699fb',
    storageBucket: 'english-mate-699fb.firebasestorage.app',
    androidClientId: '1090505053172-qe72617rir8ab22ss392ihp5rqku17bs.apps.googleusercontent.com',
    iosClientId: '1090505053172-ia0e2f5v111srr9p3oihqrokc2bakrg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwIoK1BN9rHalLwmif9waW7EbEATFDsE',
    appId: '1:1090505053172:ios:32c55f05a5a111fc551fa1',
    messagingSenderId: '1090505053172',
    projectId: 'english-mate-699fb',
    storageBucket: 'english-mate-699fb.firebasestorage.app',
    androidClientId: '1090505053172-qe72617rir8ab22ss392ihp5rqku17bs.apps.googleusercontent.com',
    iosClientId: '1090505053172-ia0e2f5v111srr9p3oihqrokc2bakrg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcBVyq4SC69m-Fpgl1fvuBIsTFmXRQlT8',
    appId: '1:1090505053172:web:d68dcc4be894a576551fa1',
    messagingSenderId: '1090505053172',
    projectId: 'english-mate-699fb',
    authDomain: 'english-mate-699fb.firebaseapp.com',
    storageBucket: 'english-mate-699fb.firebasestorage.app',
    measurementId: 'G-VTBPLEL8XL',
  );
}
